### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by xmunoz** [ossf/wg-securing-critical-projects#10]
Something to come out of the first meeting is this desire for an informal communication channel. I propose the creation of a Slack channel. Unless there are strong objections to Slack, I can do that in the coming days and send a PR to update the README with a link.

**Comment by mayakacz** [comment]
I think this is being discussed. I think ideally, this would be consistent across groups if that works: https://github.com/ossf/tac/issues/7

**Comment by xmunoz** [comment]
As someone who just dialed in to the first meeting of this WG, I don't know anything about the other working groups, or to what extent collaboration is expected.

Is the Slack discussion happening in another public forum? Is this issue an appropriate place to have that discussion? Who are the stakeholders, beyond members of this WG, required to make this decision?

**Comment by dlorenc** [comment]
Slack exists! Link is here: https://join.slack.com/t/openssf/shared_invite/zt-h4z7evg1-QYF45BuqFXnLGSVwnw9DCA
