### ISSUE TITLE
Link to meeting recordings?

### ISSUE THREAD

**Issue by xmunoz** [ossf/wg-securing-critical-projects#11]
We recorded the last meeting. Presumably we intend to post the recording somewhere public? Update the README with a link to the meeting recordings.

**Comment by dlorenc** [comment]
We just got our youtube channel here: https://www.youtube.com/channel/UCUdhiXNEBEayowJXY_v7AXQ/

I'm uploading the video today.

**Comment by dlorenc** [comment]
Ref #12
