### ISSUE TITLE
CII Census Work

### ISSUE THREAD

**Issue by dlorenc** [ossf/wg-securing-critical-projects#14]
See this proposal: https://docs.google.com/document/d/1fKoriYszCEYuNsj1v44LxfBmLEuMqjos21Yc_iEGB0w/edit

The LF/CII groups would like to find a new group to oversee, liase with and potentially support via funding, the Harvard group working on the CII Census Program. This issue can track discussion on that topic, and hopefully any formal decisions.

**Comment by david-a-wheeler** [comment]
I propose that this WG pick up three related CII activities:

1. CII Census (of critical projects)
2. CII Survey (of developers)
3. Funding for some specific work on OpenSSH/OpenBSD/Linux kernel

The first two efforts are being led by Harvard's LISH.

**Comment by dlorenc** [comment]
Thanks David, this is on the agenda for tomorrow's meeting. Some topics for discussion (aside from funding, which we're figuring out separately):

- What interactions are expected between this group and the Census team? How can we help?
- What interactions are expected between this group and the Survey? How can we help?

**Comment by dlorenc** [comment]
Also - one other question. What would adopting #3 mean before this WG has funding?

**Comment by david-a-wheeler** [comment]
It would mean that the WG could discuss what they think the project should do in the future.

The WG isn't being asked to fund the current work.

**Comment by david-a-wheeler** [comment]
I propose closing this issue. [Per the vote via Doodle (10 out of 10 voted yes)](https://doodle.com/poll/gakqkanvp92e3qn5) the CII Census has been accepted into this "securing critical projects" WG.

I think the next steps are that LISH (part of Harvard) will need to periodically report to the WG and provide feedback. I've asked Frank Nagle (Harvard) to propose to present the CII Census work status to this WG, so the WG can learn more & provide feedback. "How can we help" both ways should flow naturally from that.
