### ISSUE TITLE
Add NIST definition of critical software per EO

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-securing-critical-projects#27]
The US Executive Order on Cybersecurity (2021) required NIST to develop a definition of "critical software". That should be cited in our list of how to ID critical software.

**Comment by bureado** [comment]
For readers _en passant_, the link is: https://www.nist.gov/itl/executive-order-improving-nations-cybersecurity/critical-software-definition-explanatory

**Comment by Amir-Montazery** [comment]
NIST Definition of "critical software" was added to the readme for Identifying Critical Projects link: https://github.com/ossf/wg-securing-critical-projects/tree/main/Initiatives/Identifying-Critical-Projects
