### ISSUE TITLE
The email group doesn't appear to be public

### ISSUE THREAD

**Issue by craiglpeters** [ossf/wg-securing-critical-projects#4]
I went to the group listed here: https://github.com/ossf/wg-securing-critical-projects#communications
And the group doesn't appear to exist or be public

**Comment by craiglpeters** [comment]
I'd like to contribute, but it isn't clear how I can

**Comment by dlorenc** [comment]
It looks like permissions were misconfigured. The group was set so anyone could join, but you had to join to see messages. Anyone should be able to see and join now.

**Comment by dlorenc** [comment]
Please let me know if you have trouble!
