### ISSUE TITLE
xkcd copyright/license violation (lack of attribution) in README

### ISSUE THREAD

**Issue by pwolanin** [ossf/wg-securing-critical-projects#48]
The file: https://github.com/ossf/wg-securing-critical-projects/blob/main/README.md

Has an image obviously from https://xkcd.com/2347/ but seems to lack any attribution.  The content is licensed: https://creativecommons.org/licenses/by-nc/2.5/

**Comment by david-a-wheeler** [comment]
Sorry, just saw this. A PR would be really appreciated. We *definitely* want this properly attributed!

If you can't create a PR, let us know!!
