### ISSUE TITLE
Weekly meetings

### ISSUE THREAD

**Issue by DixonDalmeida** [ossf/wg-securing-critical-projects#5]
I would like to be part of the weekly meetings. Can someone add the required information in the Readme.md?
Also, if possible enable Discussions for this repository.

**Comment by dlorenc** [comment]
Hey!

We're working to schedule the first meeting right now. I just opened #6 to track that.

GitHub Discussions are enabled - I've never used them before so perhaps some permissions are configured. I can see them right now:

![image](https://user-images.githubusercontent.com/1714486/89653140-3128cd00-d88c-11ea-9afd-c439ee422c3e.png)

**Comment by xmunoz** [comment]
Meetings will monthly, not weekly. I think we should try to find a recurring time every month, instead of sending out a doodle every time.

**Comment by vielmetti** [comment]
Did the meeting schedule get finalized? I'm interested in joining in.

**Comment by Amir-Montazery** [comment]
I suggest closing this issue. Meeting schedule has long been finalized.
