### ISSUE TITLE
WG Charter updates

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-securing-critical-projects#52]
Hi. The OSSF TAC is seeking to get an issue(1) closed out. We want to ensure all working groups have a complete charter.md file and as I reviewed this group's file I noticed that this WG does not have a charter in place. The Tooling WG has the best example of what we'd like to see(2), it can be copied and adjusted for this WG. Can you please make a copy, review with the WG, adjust as needed, and post it into your repo? Thank you for your assistance in this matter.

(1) - https://github.com/ossf/tac/issues/9
(2) - https://github.com/ossf/wg-security-tooling/blob/main/CHARTER.md

**Comment by jeffmendoza** [comment]
https://github.com/ossf/project-template/issues/4

**Comment by jeffmendoza** [comment]
After discussion in the WG meeting today. We will wait for further wordsmithing on the template (linked above). Then we'll customize it with a pointer to our goal (https://github.com/ossf/wg-securing-critical-projects#focus) and leads (co-chairs).

**Comment by Amir-Montazery** [comment]
Charter has been updated and merged into repo.
