### ISSUE TITLE
List of Critical Projects links

### ISSUE THREAD

**Issue by edelsohn** [ossf/wg-securing-critical-projects#55]
The Google Sheet with the list of Critical Projects has non-canonical links for some projects for which I would request an update.  The Github links for Autotools, Make and GCC are mirrors that are not controlled by the projects (in fact GCC has requested assistance from Github multiple times to move the mirrors to our Github organization)

- GCC should be https://gcc.gnu.org/
(Should GCC be listed as GNU Toolchain to encompass the entire toolchain equivalent to the LLVM listing? GCC, GLIBC, Binutils, GDB)

- Make should be https://www.gnu.org/software/make/

The link for Autotools also is non-canonical, but there is no official site that encompasses all of the tools. There is no "Autotools" project -- it is term that is used to encompass the GNU Build Tools. Should the projects be listed individually?

**Comment by david-a-wheeler** [comment]
Yes, I think the tools should listed individually. The umbrella term "autotools" is widely used, though, so mentioning somewhere that "The term 'autotools' includes the following tools: automake, libtool, autoconf, ..." (I know those are part of the autotools, I don't know if others are also considered to be part).

**Comment by edelsohn** [comment]
The Github pseudo-account autotools-mirror includes autoconf, automake, gettext, libtool, and m4.

I don't know if you want to split out the GNU Toolchain projects individually (GCC, GLIBC, GDB, Binutils) but it would be more clear to refer to it as the GNU Toolchain.

**Comment by Amir-Montazery** [comment]
A very good point about the importance of considering how granular we want to be. In general, it makes sense to list out the projects.
