### ISSUE TITLE
Schedule first weekly meeting!

### ISSUE THREAD

**Issue by dlorenc** [ossf/wg-securing-critical-projects#6]
Let's shoot for the week of the August 17th. I'll setup a doodle poll and link it here.

**Comment by kimsterv** [comment]
Doodle poll: https://doodle.com/poll/cqdmkrdems8uqe6x

**Comment by dlorenc** [comment]
Well, we missed the week of the 17th :)

Doodle poll here for scheduling next week: https://doodle.com/poll/9skvp2tatc4fe78g

**Comment by dlorenc** [comment]
Scheduled for Thursday, August 27th at 9AM Pacific. See everyone then!

Info is in the README.md
