### ISSUE TITLE
The critical project `minimist` in the github is gone with 404

### ISSUE THREAD

**Issue by fredgan** [ossf/wg-securing-critical-projects#63]
Hi folks,
I found that the project `minimist` https://github.com/substack/minimist which is in the critical projects list in Row 58 is gone with 404.

Any comments or ideas about it? How to protect our critical projects?  

@david-a-wheeler

**Comment by fredgan** [comment]
Refer to: https://github.com/minimistjs/minimist/issues/22

The repo is changed to  https://github.com/minimistjs/minimist

**Comment by Amir-Montazery** [comment]
minimist is on the set of critical projects. Thank you! Feel free to comment on the new suggestions for v1.1
link here: https://docs.google.com/spreadsheets/d/1ONZ4qeMq8xmeCHX03lIgIYE4MEXVfVL6oj05lbuXTDM/edit#gid=991730401
