### ISSUE TITLE
Quick note: Linux kernel reviews

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-securing-critical-projects#8]
Quick Note:

The Linux Foundation is already funding some security audits for the Linux kernel via CommunityBridge & OSTIF: https://funding.communitybridge.org/ostif/27e54060-371f-48b6-a8fc-a0aaf96875b0/financial

I thought people in this working group might want to be aware of that!

**Comment by OSTIF-Derek** [comment]
Thank you David! And to articulate this a little further, these audits are more focused on high level policy and practices.

If we are talking about reviewing actual code in the kernel (which is a great idea!) there are no active projects with OSTIF for that.

**Comment by Amir-Montazery** [comment]
I suggest closing this issue. Links to audits and more information available on identifying security threats, security reviews repo.
